.ALIASES
X_U1            U1(+=N00092 -=N00213 V+=VCC V-=VDD OUT=VO ) CN @EXP1.SCHEMATIC1(sch_1):INS36@EVAL.uA741.Normal(chips)
R_R1            R1(1=0 2=N00213 ) CN @EXP1.SCHEMATIC1(sch_1):INS190@ANALOG.R.Normal(chips)
V_V2            V2(+=VDD -=0 ) CN @EXP1.SCHEMATIC1(sch_1):INS307@SOURCE.VDC.Normal(chips)
V_V3            V3(+=VCC -=0 ) CN @EXP1.SCHEMATIC1(sch_1):INS341@SOURCE.VDC.Normal(chips)
R_Rf            Rf(1=N00213 2=VO ) CN @EXP1.SCHEMATIC1(sch_1):INS515@ANALOG.R.Normal(chips)
V_V1            V1(+=N02496 -=0 ) CN @EXP1.SCHEMATIC1(sch_1):INS2063@SOURCE.VSIN.Normal(chips)
V_V4            V4(+=N00092 -=N02496 ) CN @EXP1.SCHEMATIC1(sch_1):INS2473@SOURCE.VDC.Normal(chips)
_    _(VCC=VCC)
_    _(VDD=VDD)
_    _(Vo=VO)
.ENDALIASES
